#version: '3.1'
#
#services:
#  db:
#    container_name: postgres-container
#    image: postgres:latest
#    restart: unless-stopped
#    environment:
#        POSTGRES_USER: mac
#        POSTGRES_PASSWORD: Bn19c0248@
#        POSTGRES_DB: scoreCard
#    ports:
#        - "5432:5432"
#    expose:
#      - "5432"
#    volumes:
#        - ./postgres-dataz:/var/lib/postgresql/data
#
#  backend:
#    build: .
#    container_name: backend-container
#    restart: always
#    ports:
#      - "8080:9000"
#    expose:
#      - "9000"
#    depends_on:
#       db:
#         condition: service_healthy
#    environment:
#          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/scoreCard
#          SPRING_DATASOURCE_USERNAME: mac
#          SPRING_DATASOURCE_PASSWORD: Bn19c0248@
#          SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    image: scorecard-backend


version: '3.1'

services:
  db:
    container_name: postgres-container
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: mac
      POSTGRES_PASSWORD: Bn19c0248@
      POSTGRES_DB: scoreCard
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./postgres-dataz:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mac"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: .
    container_name: backend-container
    restart: always
    ports:
      - "8080:9000"
    expose:
      - "9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/scoreCard
      SPRING_DATASOURCE_USERNAME: mac
      SPRING_DATASOURCE_PASSWORD: Bn19c0248@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    image: scorecard-backend





